# Model arguments
model_name_or_path: dataeaze/RegLLM-checklist-creation-3b-quant
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
use_peft: true
load_in_4bit: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

dataset_mixer:
  dataeaze/checklists_preference_train_dataset_llama_format: 1.0
dataset_splits:
- train

preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.1
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
log_level: info
logging_steps: 100
lr_scheduler_type: linear 
max_length: 2048
max_prompt_length: 1024 
num_train_epochs: 3
optim: adamw_8bit
output_dir: checklist_dpo_with_hf_v0 # It is handy to append `hub_model_revision` to keep track of your local experiments
per_device_train_batch_size: 1
# push_to_hub: true
save_strategy: steps
save_steps: 2000
seed: 42
warmup_ratio: 0.1
weight_decay: 0.01